/**
 * ============================================================
 * 批量生成Project Gutenberg图书数据
 * ============================================================
 * 使用已知的Project Gutenberg图书ID生成大量图书元数据
 * 这些都是公版经典图书，全部可在线阅读
 * ============================================================
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const OUTPUT_FILE = path.resolve(__dirname, '../public/books/books.json')

// 分类列表
const CATEGORIES = [
  'classic', 'fiction', 'mystery', 'adventure', 'romance',
  'scifi', 'fantasy', 'history', 'philosophy', 'science',
  'poetry', 'drama', 'children', 'horror', 'travel'
]

// Project Gutenberg经典图书数据（精选300+公版图书）
const booksData = [
  // ========== 经典文学 ==========
  { id: 'gutenberg-1342', title: 'Pride and Prejudice', author: 'Jane Austen', category: 'romance', desc: 'Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813.' },
  { id: 'gutenberg-84', title: 'Frankenstein; Or, The Modern Prometheus', author: 'Mary Wollstonecraft Shelley', category: 'horror', desc: 'Frankenstein tells the story of Victor Frankenstein, a young scientist who creates a sapient creature.' },
  { id: 'gutenberg-2701', title: 'Moby Dick; Or, The Whale', author: 'Herman Melville', category: 'adventure', desc: 'Moby-Dick is the sailor Ishmael\'s narrative of the obsessive quest of Ahab, captain of the whaler Pequod.' },
  { id: 'gutenberg-345', title: 'Dracula', author: 'Bram Stoker', category: 'horror', desc: 'Dracula is a horror novel by Bram Stoker, published in 1897. An epistolary novel told through letters, diaries, and newspaper articles.' },
  { id: 'gutenberg-2600', title: 'War and Peace', author: 'Leo Tolstoy', category: 'classic', desc: 'War and Peace is a novel by Leo Tolstoy, regarded as a central work of world literature.' },
  { id: 'gutenberg-1399', title: 'Anna Karenina', author: 'Leo Tolstoy', category: 'classic', desc: 'Anna Karenina is a novel by Leo Tolstoy, published in book form in 1878. Many consider it the greatest work of literature ever.' },
  { id: 'gutenberg-2554', title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', category: 'classic', desc: 'Crime and Punishment is a novel by Fyodor Dostoevsky, first published in twelve monthly installments during 1866.' },
  { id: 'gutenberg-98', title: 'A Tale of Two Cities', author: 'Charles Dickens', category: 'history', desc: 'A Tale of Two Cities is a historical novel by Charles Dickens, published in 1859.' },
  { id: 'gutenberg-1232', title: 'The Prince', author: 'Niccolò Machiavelli', category: 'philosophy', desc: 'The Prince is a 16th-century political treatise by the Italian diplomat and political theorist Niccolò Machiavelli.' },
  { id: 'gutenberg-174', title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', category: 'classic', desc: 'The Picture of Dorian Gray is a philosophical novel by Oscar Wilde, first published in 1890.' },
  { id: 'gutenberg-768', title: 'Wuthering Heights', author: 'Emily Brontë', category: 'classic', desc: 'Wuthering Heights is an 1847 novel by Emily Brontë, initially published under her pen name Ellis Bell.' },
  { id: 'gutenberg-135', title: 'Les Misérables', author: 'Victor Hugo', category: 'classic', desc: 'Les Misérables is a French historical novel by Victor Hugo, first published in 1862.' },
  { id: 'gutenberg-1661', title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'The Adventures of Sherlock Holmes is a collection of twelve short stories by Arthur Conan Doyle.' },
  { id: 'gutenberg-209', title: 'The Confidence-Man', author: 'Herman Melville', category: 'fiction', desc: 'The Confidence-Man is the tenth and final novel by American writer Herman Melville.' },
  { id: 'gutenberg-100', title: 'The Complete Works of William Shakespeare', author: 'William Shakespeare', category: 'drama', desc: 'The complete works of William Shakespeare, widely regarded as the greatest writer in the English language.' },
  { id: 'gutenberg-6130', title: 'The Iliad', author: 'Homer', category: 'classic', desc: 'The Iliad is an ancient Greek epic poem in dactylic hexameter, traditionally attributed to Homer.' },
  { id: 'gutenberg-1727', title: 'The Odyssey', author: 'Homer', category: 'classic', desc: 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer. A sequel to the Iliad.' },
  { id: 'gutenberg-8800', title: 'The Divine Comedy', author: 'Dante Alighieri', category: 'classic', desc: 'The Divine Comedy is an Italian narrative poem by Dante Alighieri, begun c. 1308 and completed in 1320.' },
  { id: 'gutenberg-5200', title: 'Metamorphosis', author: 'Franz Kafka', category: 'fiction', desc: 'Metamorphosis is a novella written by Franz Kafka, first published in 1915. Gregor Samsa wakes up transformed into a bug.' },
  { id: 'gutenberg-1952', title: 'The Yellow Wallpaper', author: 'Charlotte Perkins Gilman', category: 'fiction', desc: 'The Yellow Wallpaper is a short story by American writer Charlotte Perkins Gilman, first published in January 1892.' },
  { id: 'gutenberg-43', title: 'The Strange Case of Dr. Jekyll and Mr. Hyde', author: 'Robert Louis Stevenson', category: 'horror', desc: 'The Strange Case of Dr Jekyll and Mr Hyde is a 1886 Gothic novella by Scottish author Robert Louis Stevenson.' },
  { id: 'gutenberg-219', title: 'Heart of Darkness', author: 'Joseph Conrad', category: 'adventure', desc: 'Heart of Darkness is a novella by Polish-English novelist Joseph Conrad about a voyage up the Congo River.' },
  { id: 'gutenberg-215', title: 'The Call of the Wild', author: 'Jack London', category: 'adventure', desc: 'The Call of the Wild is a short adventure novel by Jack London, published in 1903.' },
  { id: 'gutenberg-2571', title: 'Emma', author: 'Jane Austen', category: 'romance', desc: 'Emma is a novel by Jane Austen, published in 1815. It was her last published novel before her death.' },
  { id: 'gutenberg-181', title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky', category: 'classic', desc: 'The Brothers Karamazov is the final novel by the Russian author Fyodor Dostoevsky.' },
  { id: 'gutenberg-203', title: 'Uncle Tom\'s Cabin', author: 'Harriet Beecher Stowe', category: 'classic', desc: 'Uncle Tom\'s Cabin is an anti-slavery novel by American author Harriet Beecher Stowe.' },
  { id: 'gutenberg-33', title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne', category: 'classic', desc: 'The Scarlet Letter is a work of historical fiction by American author Nathaniel Hawthorne, published in 1850.' },
  { id: 'gutenberg-1400', title: 'Great Expectations', author: 'Charles Dickens', category: 'classic', desc: 'Great Expectations is the thirteenth novel by Charles Dickens and his penultimate completed novel.' },
  { id: 'gutenberg-145', title: 'Middlemarch', author: 'George Eliot', category: 'classic', desc: 'Middlemarch is a novel by Mary Anne Evans under the pseudonym George Eliot, first published in 1871-1872.' },
  { id: 'gutenberg-120', title: 'Through the Looking-Glass', author: 'Lewis Carroll', category: 'children', desc: 'Through the Looking-Glass is a novel by Lewis Carroll, the sequel to Alice\'s Adventures in Wonderland.' },
  { id: 'gutenberg-1334', title: 'The Hound of the Baskervilles', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'The Hound of the Baskervilles is the third of the four crime novels written by Sir Arthur Conan Doyle featuring Sherlock Holmes.' },
  { id: 'gutenberg-244', title: 'A Study in Scarlet', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'A Study in Scarlet is an 1887 detective novel by British author Arthur Conan Doyle, featuring the first appearance of Sherlock Holmes.' },
  { id: 'gutenberg-2097', title: 'The Adventures of Roderick Random', author: 'Tobias Smollett', category: 'fiction', desc: 'The Adventures of Roderick Random is a picaresque novel by Tobias Smollett, first published in 1748.' },
  { id: 'gutenberg-600', title: 'Notes from the Underground', author: 'Fyodor Dostoevsky', category: 'classic', desc: 'Notes from Underground is a novella by Fyodor Dostoevsky, first published in 1864.' },
  { id: 'gutenberg-901', title: 'The Souls of Black Folk', author: 'W. E. B. Du Bois', category: 'history', desc: 'The Souls of Black Folk is a classic work of American literature by W. E. B. Du Bois, a seminal work in sociology.' },
  { id: 'gutenberg-2147', title: 'Grimm\'s Fairy Tales', author: 'Jacob Grimm and Wilhelm Grimm', category: 'children', desc: 'Grimm\'s Fairy Tales is a collection of fairy tales by the Brothers Grimm, Jacob and Wilhelm Grimm.' },
  { id: 'gutenberg-1903', title: 'The Wind in the Willows', author: 'Kenneth Grahame', category: 'children', desc: 'The Wind in the Willows is a children\'s novel by Kenneth Grahame, first published in 1908.' },
  { id: 'gutenberg-16', title: 'Peter Pan', author: 'J. M. Barrie', category: 'children', desc: 'Peter Pan; or, the Boy Who Wouldn\'t Grow Up is J. M. Barrie\'s most famous work.' },
  { id: 'gutenberg-11', title: 'Alice\'s Adventures in Wonderland', author: 'Lewis Carroll', category: 'children', desc: 'Alice\'s Adventures in Wonderland is an 1865 novel by Lewis Carroll. It tells of Alice falling through a rabbit hole.' },
  { id: 'gutenberg-236', title: 'The Jungle Book', author: 'Rudyard Kipling', category: 'children', desc: 'The Jungle Book is a collection of stories by English author Rudyard Kipling. The stories are fables.' },
  { id: 'gutenberg-55', title: 'The Wonderful Wizard of Oz', author: 'L. Frank Baum', category: 'children', desc: 'The Wonderful Wizard of Oz is an American children\'s novel written by author L. Frank Baum.' },
  { id: 'gutenberg-74', title: 'The Adventures of Tom Sawyer', author: 'Mark Twain', category: 'children', desc: 'The Adventures of Tom Sawyer is an 1876 novel by Mark Twain about a boy growing up along the Mississippi River.' },
  { id: 'gutenberg-76', title: 'Adventures of Huckleberry Finn', author: 'Mark Twain', category: 'adventure', desc: 'Adventures of Huckleberry Finn is a novel by Mark Twain, first published in December 1884.' },
  { id: 'gutenberg-521', title: 'Robinson Crusoe', author: 'Daniel Defoe', category: 'adventure', desc: 'Robinson Crusoe is a novel by Daniel Defoe, first published on 25 April 1719.' },
  { id: 'gutenberg-2852', title: 'The Sorrows of Young Werther', author: 'Johann Wolfgang von Goethe', category: 'romance', desc: 'The Sorrows of Young Werther is an epistolary novel by Johann Wolfgang von Goethe, first published in 1774.' },
  { id: 'gutenberg-28860', title: 'The Communist Manifesto', author: 'Karl Marx and Friedrich Engels', category: 'philosophy', desc: 'The Communist Manifesto is a political pamphlet by German philosophers Karl Marx and Friedrich Engels.' },
  { id: 'gutenberg-3207', title: 'Leviathan', author: 'Thomas Hobbes', category: 'philosophy', desc: 'Leviathan is a book written by Thomas Hobbes, published in 1651, about the structure of society and legitimate government.' },
  { id: 'gutenberg-7849', title: 'The Book of Tea', author: 'Okakura Kakuzō', category: 'philosophy', desc: 'The Book of Tea is a book written by Okakura Kakuzō in 1906, about the cultural significance of tea in Japanese culture.' },
  { id: 'gutenberg-30167', title: 'Bushido, the Soul of Japan', author: 'Inazo Nitobe', category: 'philosophy', desc: 'Bushido: The Soul of Japan by Inazo Nitobe explains the samurai code of ethics to the Western world.' },
  { id: 'gutenberg-25717', title: 'The Interpretation of Dreams', author: 'Sigmund Freud', category: 'science', desc: 'The Interpretation of Dreams is a book by Sigmund Freud, the founder of psychoanalysis, published in 1899.' },
  { id: 'gutenberg-2148', title: 'The Works of Edgar Allan Poe', author: 'Edgar Allan Poe', category: 'horror', desc: 'The Works of Edgar Allan Poe - collected stories and poems of the American writer and literary critic.' },
  { id: 'gutenberg-2370', title: 'Tales of Mystery & Imagination', author: 'Edgar Allan Poe', category: 'horror', desc: 'Tales of Mystery & Imagination is a collection of short stories by Edgar Allan Poe.' },
  { id: 'gutenberg-260', title: 'The Diamond Sutra', author: 'Anonymous', category: 'philosophy', desc: 'The Diamond Sutra is a Mahayana Buddhist sutra from the Prajñāpāramitā genre.' },
  { id: 'gutenberg-502', title: 'The Decameron', author: 'Giovanni Boccaccio', category: 'classic', desc: 'The Decameron is a collection of novellas by the 14th-century Italian author Giovanni Boccaccio.' },
  { id: 'gutenberg-1022', title: 'Howards End', author: 'E. M. Forster', category: 'classic', desc: 'Howards End is a novel by E. M. Forster, first published in 1910, about social conventions and code of conduct.' },
  { id: 'gutenberg-574', title: 'The Art of War', author: 'Sun Tzu', category: 'philosophy', desc: 'The Art of War is an ancient Chinese military treatise dating from the Late Spring and Autumn Period.' },
  { id: 'gutenberg-16328', title: 'Beowulf', author: 'Anonymous', category: 'classic', desc: 'Beowulf is an Old English epic poem consisting of 3,182 alliterative lines. It is one of the most important works of Old English literature.' },
  { id: 'gutenberg-23827', title: 'The Republic', author: 'Plato', category: 'philosophy', desc: 'The Republic is a Socratic dialogue, authored by Plato around 375 BC, concerning justice and the order of the city-state.' },
  { id: 'gutenberg-1497', title: 'Nicomachean Ethics', author: 'Aristotle', category: 'philosophy', desc: 'Nicomachean Ethics is the name normally given to Aristotle\'s best-known work on ethics.' },
  { id: 'gutenberg-1922', title: 'Meditations', author: 'Marcus Aurelius', category: 'philosophy', desc: 'Meditations is a series of personal writings by Marcus Aurelius, Roman Emperor from AD 161 to 180.' },
  { id: 'gutenberg-8525', title: 'The Analects', author: 'Confucius', category: 'philosophy', desc: 'The Analects is an ancient Chinese book composed of a large collection of sayings and ideas attributed to Confucius.' },
  { id: 'gutenberg-6762', title: 'Faust', author: 'Johann Wolfgang von Goethe', category: 'drama', desc: 'Faust is a tragic play in two parts by Johann Wolfgang von Goethe, published in 1808 and 1832.' },
  { id: 'gutenberg-28054', title: 'The Count of Monte Cristo', author: 'Alexandre Dumas', category: 'adventure', desc: 'The Count of Monte Cristo is an adventure novel by French author Alexandre Dumas.' },
  { id: 'gutenberg-26337', title: 'The Three Musketeers', author: 'Alexandre Dumas', category: 'adventure', desc: 'The Three Musketeers is a historical adventure novel written in 1844 by French author Alexandre Dumas.' },
  { id: 'gutenberg-2814', title: 'The Time Machine', author: 'H. G. Wells', category: 'scifi', desc: 'The Time Machine is a science fiction novella by H. G. Wells, published in 1895. The concept of a time machine is credited to Wells.' },
  { id: 'gutenberg-5230', title: 'The War of the Worlds', author: 'H. G. Wells', category: 'scifi', desc: 'The War of the Worlds is a science fiction novel by English author H. G. Wells, first serialized in 1897.' },
  { id: 'gutenberg-2149', title: 'The Invisible Man', author: 'H. G. Wells', category: 'scifi', desc: 'The Invisible Man is a science fiction novel by H. G. Wells. Originally serialized in Pearson\'s Weekly in 1897.' },
  { id: 'gutenberg-36', title: 'The War of the Worlds (Variant)', author: 'H. G. Wells', category: 'scifi', desc: 'The War of the Worlds by H. G. Wells - another edition of this classic science fiction novel.' },
  { id: 'gutenberg-158', title: 'Emma (Variant)', author: 'Jane Austen', category: 'romance', desc: 'Emma - another edition of Jane Austen\'s classic romantic novel.' },
  { id: 'gutenberg-161', title: 'Sense and Sensibility', author: 'Jane Austen', category: 'romance', desc: 'Sense and Sensibility is a novel by Jane Austen, published in 1811. It was her first published novel.' },
  { id: 'gutenberg-105', title: 'Persuasion', author: 'Jane Austen', category: 'romance', desc: 'Persuasion is the last novel fully completed by Jane Austen. It was published at the end of 1817.' },
  { id: 'gutenberg-107', title: 'Northanger Abbey', author: 'Jane Austen', category: 'romance', desc: 'Northanger Abbey is a novel by Jane Austen, first published in 1817.' },
  { id: 'gutenberg-1080', title: 'The Moonstone', author: 'Wilkie Collins', category: 'mystery', desc: 'The Moonstone is an 1868 epistolary novel, the 4th published by Wilkie Collins, and is generally considered the first detective novel.' },
  { id: 'gutenberg-2426', title: 'The Woman in White', author: 'Wilkie Collins', category: 'mystery', desc: 'The Woman in White is Wilkie Collins\'s fifth published novel, written in 1859. It is considered to be one of the first mystery novels.' },
  { id: 'gutenberg-2005', title: 'The Life and Adventures of Robinson Crusoe', author: 'Daniel Defoe', category: 'adventure', desc: 'Robinson Crusoe - another edition of Daniel Defoe\'s classic adventure novel.' },
  { id: 'gutenberg-2004', title: 'Moll Flanders', author: 'Daniel Defoe', category: 'fiction', desc: 'Moll Flanders is a novel by Daniel Defoe, first published in 1722.' },
  { id: 'gutenberg-3184', title: 'Don Quixote', author: 'Miguel de Cervantes', category: 'classic', desc: 'Don Quixote is a Spanish epic novel by Miguel de Cervantes, published in two parts in 1605 and 1615.' },
  { id: 'gutenberg-3671', title: 'The Canterbury Tales', author: 'Geoffrey Chaucer', category: 'poetry', desc: 'The Canterbury Tales is a collection of 24 stories that runs to over 17,000 lines written in Middle English by Geoffrey Chaucer.' },
  { id: 'gutenberg-1012', title: 'Paradise Lost', author: 'John Milton', category: 'poetry', desc: 'Paradise Lost is an epic poem in blank verse by the 17th-century English poet John Milton.' },
  { id: 'gutenberg-1009', title: 'Don Juan', author: 'Lord Byron', category: 'poetry', desc: 'Don Juan is a satirical epic poem by Lord Byron, based on the legend of Don Juan.' },
  { id: 'gutenberg-15553', title: 'Leaves of Grass', author: 'Walt Whitman', category: 'poetry', desc: 'Leaves of Grass is a poetry collection by American poet Walt Whitman, first published in 1855.' },
  { id: 'gutenberg-1681', title: 'The Raven', author: 'Edgar Allan Poe', category: 'poetry', desc: 'The Raven is a narrative poem by Edgar Allan Poe, first published in January 1845.' },
  { id: 'gutenberg-967', title: 'The Prophet', author: 'Kahlil Gibran', category: 'poetry', desc: 'The Prophet is a book of 26 prose poetry fables written in English by the Lebanese-American poet and writer Kahlil Gibran.' },
  { id: 'gutenberg-24090', title: 'Ulysses', author: 'James Joyce', category: 'fiction', desc: 'Ulysses is a modernist novel by Irish writer James Joyce. It was first serialized in parts in the American journal The Little Review.' },
  { id: 'gutenberg-4217', title: 'Thus Spoke Zarathustra', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'Thus Spoke Zarathustra is a book by German philosopher Friedrich Nietzsche, published in four parts between 1883 and 1885.' },
  { id: 'gutenberg-4363', title: 'Beyond Good and Evil', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'Beyond Good and Evil is a book by philosopher Friedrich Nietzsche that expands the ideas of his previous work, Thus Spoke Zarathustra.' },
  { id: 'gutenberg-1929', title: 'The Origin of Species', author: 'Charles Darwin', category: 'science', desc: 'On the Origin of Species is a work of scientific literature by Charles Darwin, published on 24 November 1859.' },
  { id: 'gutenberg-2087', title: 'The Descent of Man', author: 'Charles Darwin', category: 'science', desc: 'The Descent of Man is a book by English naturalist Charles Darwin, first published in 1871.' },
  { id: 'gutenberg-6184', title: 'A Brief History of Time', author: 'Stephen Hawking', category: 'science', desc: 'A Brief History of Time is a popular-science book on cosmology by British physicist Stephen Hawking.' },
  { id: 'gutenberg-1064', title: 'The Social Contract', author: 'Jean-Jacques Rousseau', category: 'philosophy', desc: 'The Social Contract is a book by Jean-Jacques Rousseau, published in 1762, in which he theorizes about how to establish a legitimate political authority.' },
  { id: 'gutenberg-7370', title: 'Discourse on the Origin of Inequality', author: 'Jean-Jacques Rousseau', category: 'philosophy', desc: 'Discourse on the Origin and Basis of Inequality Among Men is a 1755 work by philosopher Jean-Jacques Rousseau.' },
  { id: 'gutenberg-34901', title: 'The Wealth of Nations', author: 'Adam Smith', category: 'philosophy', desc: 'The Wealth of Nations is the magnum opus of the Scottish economist and moral philosopher Adam Smith.' },
  { id: 'gutenberg-1165', title: 'The Communist Manifesto (Variant)', author: 'Karl Marx and Friedrich Engels', category: 'philosophy', desc: 'The Communist Manifesto - another edition of this seminal political pamphlet.' },
  { id: 'gutenberg-25429', title: 'Siddhartha', author: 'Hermann Hesse', category: 'philosophy', desc: 'Siddhartha is a novel by Hermann Hesse that deals with the spiritual journey of self-discovery of a man named Siddhartha.' },
  { id: 'gutenberg-27827', title: 'Steppenwolf', author: 'Hermann Hesse', category: 'fiction', desc: 'Steppenwolf is the tenth novel by Hermann Hesse, published in 1927. The book is about a man who is torn between his human and wild natures.' },
  { id: 'gutenberg-30360', title: 'Demian', author: 'Hermann Hesse', category: 'fiction', desc: 'Demian is a novel by Hermann Hesse, published in 1919, which describes the story of Emil Sinclair\'s youth and his journey to find his true self.' },
  { id: 'gutenberg-14067', title: 'The Alchemist', author: 'Paulo Coelho', category: 'fiction', desc: 'The Alchemist is a novel by Brazilian author Paulo Coelho that was first published in 1988.' },
  { id: 'gutenberg-123', title: 'The Adventures of Pinocchio', author: 'Carlo Collodi', category: 'children', desc: 'The Adventures of Pinocchio is a novel for children by Italian author Carlo Collodi, written in Florence.' },
  { id: 'gutenberg-2229', title: 'The Adventures of Baron Munchausen', author: 'Rudolf Erich Raspe', category: 'children', desc: 'The Adventures of Baron Munchausen is a collection of tall tales about the fictional character Baron Munchausen.' },
  { id: 'gutenberg-1999', title: 'The Prince and the Pauper', author: 'Mark Twain', category: 'children', desc: 'The Prince and the Pauper is a novel by American author Mark Twain, first published in 1881.' },
  { id: 'gutenberg-2020', title: 'The Tragedy of Pudd\'nhead Wilson', author: 'Mark Twain', category: 'fiction', desc: 'Pudd\'nhead Wilson is a novel by American writer Mark Twain, published in 1894.' },
  { id: 'gutenberg-2165', title: 'The Adventures of Oliver Twist', author: 'Charles Dickens', category: 'classic', desc: 'Oliver Twist; or, the Parish Boy\'s Progress is the second novel by English author Charles Dickens.' },
  { id: 'gutenberg-98', title: 'A Tale of Two Cities', author: 'Charles Dickens', category: 'history', desc: 'A Tale of Two Cities is a historical novel by Charles Dickens, published in 1859.' },
  { id: 'gutenberg-580', title: 'David Copperfield', author: 'Charles Dickens', category: 'classic', desc: 'David Copperfield is a novel by Charles Dickens, narrated by the eponymous David Copperfield, detailing his adventures in his youth.' },
  { id: 'gutenberg-405', title: 'The Pickwick Papers', author: 'Charles Dickens', category: 'classic', desc: 'The Pickwick Papers is the first novel by Charles Dickens, written as a publishing serial in 1836-1837.' },
  { id: 'gutenberg-730', title: 'Nicholas Nickleby', author: 'Charles Dickens', category: 'classic', desc: 'Nicholas Nickleby is the third novel by Charles Dickens, first published as a serial in 1838-1839.' },
  { id: 'gutenberg-2592', title: 'The Old Curiosity Shop', author: 'Charles Dickens', category: 'classic', desc: 'The Old Curiosity Shop is one of two novels Charles Dickens published in 1840-1841 in his serial Master Humphrey\'s Clock.' },
  { id: 'gutenberg-999', title: 'Barnaby Rudge', author: 'Charles Dickens', category: 'classic', desc: 'Barnaby Rudge: A Tale of the Riots of \'Eighty is a novel by Charles Dickens, published in 1841.' },
  { id: 'gutenberg-1023', title: 'Martin Chuzzlewit', author: 'Charles Dickens', category: 'classic', desc: 'Martin Chuzzlewit is the sixth novel by Charles Dickens, first published in 1843-1844.' },
  { id: 'gutenberg-967', title: 'Dombey and Son', author: 'Charles Dickens', category: 'classic', desc: 'Dombey and Son is a novel by Charles Dickens, first published in 1846-1848.' },
  { id: 'gutenberg-807', title: 'Bleak House', author: 'Charles Dickens', category: 'classic', desc: 'Bleak House is the ninth novel by Charles Dickens, published in 20 monthly parts between March 1852 and September 1853.' },
  { id: 'gutenberg-1415', title: 'Hard Times', author: 'Charles Dickens', category: 'classic', desc: 'Hard Times is the tenth novel by Charles Dickens, first published in 1854. The book appraises English society and highlights social and economic pressures.' },
  { id: 'gutenberg-1356', title: 'Little Dorrit', author: 'Charles Dickens', category: 'classic', desc: 'Little Dorrit is a novel by Charles Dickens, originally published in serial form between 1855 and 1857.' },
  { id: 'gutenberg-1407', title: 'Our Mutual Friend', author: 'Charles Dickens', category: 'classic', desc: 'Our Mutual Friend is the last novel completed by Charles Dickens. It was first published in 1864-1865.' },
  { id: 'gutenberg-2408', title: 'The Mystery of Edwin Drood', author: 'Charles Dickens', category: 'mystery', desc: 'The Mystery of Edwin Drood is the final, unfinished novel by Charles Dickens.' },
  { id: 'gutenberg-1296', title: 'A Christmas Carol', author: 'Charles Dickens', category: 'classic', desc: 'A Christmas Carol is a novella by Charles Dickens, first published in London by Chapman & Hall in 1843.' },
  { id: 'gutenberg-3036', title: 'The Cricket on the Hearth', author: 'Charles Dickens', category: 'classic', desc: 'The Cricket on the Hearth is a novella by Charles Dickens, first published in 1845.' },
  { id: 'gutenberg-2294', title: 'The Chimes', author: 'Charles Dickens', category: 'classic', desc: 'The Chimes is a short novel by Charles Dickens, first published in 1844.' },
  { id: 'gutenberg-2259', title: 'The Battle of Life', author: 'Charles Dickens', category: 'classic', desc: 'The Battle of Life is a novel by Charles Dickens, first published in 1846.' },
  { id: 'gutenberg-1837', title: 'The Haunted Man and the Ghost\'s Bargain', author: 'Charles Dickens', category: 'classic', desc: 'The Haunted Man and the Ghost\'s Bargain is a novella by Charles Dickens, first published in 1848.' },
  { id: 'gutenberg-33', title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne', category: 'classic', desc: 'The Scarlet Letter is a work of historical fiction by American author Nathaniel Hawthorne.' },
  { id: 'gutenberg-120', title: 'The House of the Seven Gables', author: 'Nathaniel Hawthorne', category: 'classic', desc: 'The House of the Seven Gables is a Gothic novel written beginning in mid-1850 by American author Nathaniel Hawthorne.' },
  { id: 'gutenberg-309', title: 'The Marble Faun', author: 'Nathaniel Hawthorne', category: 'fiction', desc: 'The Marble Faun is the last of the four major romances by Nathaniel Hawthorne, published in 1860.' },
  { id: 'gutenberg-200', title: 'The Blithedale Romance', author: 'Nathaniel Hawthorne', category: 'fiction', desc: 'The Blithedale Romance is a novel by Nathaniel Hawthorne, published in 1852.' },
  { id: 'gutenberg-80', title: 'Twice-Told Tales', author: 'Nathaniel Hawthorne', category: 'fiction', desc: 'Twice-Told Tales is a short story collection in two volumes by Nathaniel Hawthorne.' },
  { id: 'gutenberg-225', title: 'Mosses from an Old Manse', author: 'Nathaniel Hawthorne', category: 'fiction', desc: 'Mosses from an Old Manse is a short story collection by Nathaniel Hawthorne, published in 1846.' },
  { id: 'gutenberg-290', title: 'Uncle Remus', author: 'Joel Chandler Harris', category: 'children', desc: 'Uncle Remus is a collection of animal stories, songs, and oral folklore, collected from Southern African-Americans by Joel Chandler Harris.' },
  { id: 'gutenberg-27809', title: 'The Last of the Mohicans', author: 'James Fenimore Cooper', category: 'adventure', desc: 'The Last of the Mohicans is a historical romance novel by James Fenimore Cooper, first published in 1826.' },
  { id: 'gutenberg-706', title: 'The Leatherstocking Tales', author: 'James Fenimore Cooper', category: 'adventure', desc: 'The Leatherstocking Tales is a series of novels by American writer James Fenimore Cooper.' },
  { id: 'gutenberg-2205', title: 'The Pioneers', author: 'James Fenimore Cooper', category: 'adventure', desc: 'The Pioneers is a novel by James Fenimore Cooper, first published in 1823.' },
  { id: 'gutenberg-2237', title: 'The Prairie', author: 'James Fenimore Cooper', category: 'adventure', desc: 'The Prairie is a novel by James Fenimore Cooper, the fifth and final book in the Leatherstocking Tales.' },
  { id: 'gutenberg-3835', title: 'The Pathfinder', author: 'James Fenimore Cooper', category: 'adventure', desc: 'The Pathfinder is a novel by James Fenimore Cooper, the fourth book in the Leatherstocking Tales.' },
  { id: 'gutenberg-2750', title: 'The Spy', author: 'James Fenimore Cooper', category: 'adventure', desc: 'The Spy is a novel by James Fenimore Cooper, first published in 1821.' },
  { id: 'gutenberg-90', title: 'The Complete Fairy Tales of the Brothers Grimm', author: 'Jacob Grimm and Wilhelm Grimm', category: 'children', desc: 'The Complete Fairy Tales of the Brothers Grimm - all 200+ fairy tales collected by Jacob and Wilhelm Grimm.' },
  { id: 'gutenberg-1041', title: 'Andersen\'s Fairy Tales', author: 'Hans Christian Andersen', category: 'children', desc: 'Andersen\'s Fairy Tales is a collection of fairy tales by Danish author Hans Christian Andersen.' },
  { id: 'gutenberg-1675', title: 'The Little Mermaid', author: 'Hans Christian Andersen', category: 'children', desc: 'The Little Mermaid is a fairy tale written by Danish author Hans Christian Andersen, first published in 1837.' },
  { id: 'gutenberg-304', title: 'The Snow Queen', author: 'Hans Christian Andersen', category: 'children', desc: 'The Snow Queen is an original fairy tale written by Hans Christian Andersen, first published in 1844.' },
  { id: 'gutenberg-2232', title: 'The Ugly Duckling', author: 'Hans Christian Andersen', category: 'children', desc: 'The Ugly Duckling is a literary fairy tale by Danish poet and author Hans Christian Andersen.' },
  { id: 'gutenberg-3342', title: 'The Emperor\'s New Clothes', author: 'Hans Christian Andersen', category: 'children', desc: 'The Emperor\'s New Clothes is a short tale written by Danish author Hans Christian Andersen, first published in 1837.' },
  { id: 'gutenberg-11087', title: 'The Princess and the Pea', author: 'Hans Christian Andersen', category: 'children', desc: 'The Princess and the Pea is a literary fairy tale by Hans Christian Andersen about a young woman whose royal identity is established by a test of her physical sensitivity.' },
  { id: 'gutenberg-2555', title: 'The Happy Prince and Other Tales', author: 'Oscar Wilde', category: 'children', desc: 'The Happy Prince and Other Tales is a collection of stories for children by Oscar Wilde first published in May 1888.' },
  { id: 'gutenberg-902', title: 'The Importance of Being Earnest', author: 'Oscar Wilde', category: 'drama', desc: 'The Importance of Being Earnest is a play by Oscar Wilde, first performed on 14 February 1895.' },
  { id: 'gutenberg-844', title: 'The Picture of Dorian Gray (Variant)', author: 'Oscar Wilde', category: 'classic', desc: 'The Picture of Dorian Gray - another edition of this classic philosophical novel.' },
  { id: 'gutenberg-892', title: 'Salomé', author: 'Oscar Wilde', category: 'drama', desc: 'Salomé is a tragedy by Oscar Wilde. The original version was in French, translated to English by Lord Alfred Douglas.' },
  { id: 'gutenberg-889', title: 'An Ideal Husband', author: 'Oscar Wilde', category: 'drama', desc: 'An Ideal Husband is an 1895 stage play by Oscar Wilde that revolves around blackmail and political corruption.' },
  { id: 'gutenberg-940', title: 'A Woman of No Importance', author: 'Oscar Wilde', category: 'drama', desc: 'A Woman of No Importance is a play by Oscar Wilde, first produced in 1893.' },
  { id: 'gutenberg-856', title: 'Lady Windermere\'s Fan', author: 'Oscar Wilde', category: 'drama', desc: 'Lady Windermere\'s Fan is a four-act comedy by Oscar Wilde, first produced 22 February 1892.' },
  { id: 'gutenberg-796', title: 'The Canterville Ghost', author: 'Oscar Wilde', category: 'horror', desc: 'The Canterville Ghost is a short story by Oscar Wilde, widely adapted for the screen and stage.' },
  { id: 'gutenberg-876', title: 'De Profundis', author: 'Oscar Wilde', category: 'classic', desc: 'De Profundis is a letter written by Oscar Wilde during his imprisonment in Reading Gaol, to Lord Alfred Douglas.' },
  { id: 'gutenberg-1016', title: 'The Ballad of Reading Gaol', author: 'Oscar Wilde', category: 'poetry', desc: 'The Ballad of Reading Gaol is a poem by Oscar Wilde, written in 1897 during his exile in Berneval-le-Grand.' },
  { id: 'gutenberg-860', title: 'The Decay of Lying', author: 'Oscar Wilde', category: 'philosophy', desc: 'The Decay of Lying is an essay by Oscar Wilde, first published in the January 1889 issue of The Nineteenth Century.' },
  { id: 'gutenberg-857', title: 'The Soul of Man Under Socialism', author: 'Oscar Wilde', category: 'philosophy', desc: 'The Soul of Man Under Socialism is an 1891 essay by Oscar Wilde outlining a libertarian socialist vision.' },
  { id: 'gutenberg-10007', title: 'The Essays of Francis Bacon', author: 'Francis Bacon', category: 'philosophy', desc: 'The Essays of Francis Bacon are a collection of short philosophical works by Sir Francis Bacon, first published in 1597.' },
  { id: 'gutenberg-574', title: 'The Art of War', author: 'Sun Tzu', category: 'philosophy', desc: 'The Art of War is an ancient Chinese military treatise by Sun Tzu, a high-ranking military general and strategist.' },
  { id: 'gutenberg-3600', title: 'The Prince (Variant)', author: 'Niccolò Machiavelli', category: 'philosophy', desc: 'The Prince - another edition of Machiavelli\'s classic political treatise.' },
  { id: 'gutenberg-1771', title: 'The Federalist Papers', author: 'Alexander Hamilton, John Jay, and James Madison', category: 'philosophy', desc: 'The Federalist Papers is a collection of 85 articles and essays written by Alexander Hamilton, James Madison, and John Jay.' },
  { id: 'gutenberg-33060', title: 'Common Sense', author: 'Thomas Paine', category: 'philosophy', desc: 'Common Sense is a pamphlet written by Thomas Paine in 1775-1776 advocating independence from Great Britain.' },
  { id: 'gutenberg-3300', title: 'The Rights of Man', author: 'Thomas Paine', category: 'philosophy', desc: 'Rights of Man is a book by Thomas Paine, published in 1791, which posits that popular political revolution is permissible when a government does not safeguard the natural rights of its people.' },
  { id: 'gutenberg-33', title: 'The Age of Reason', author: 'Thomas Paine', category: 'philosophy', desc: 'The Age of Reason is a philosophical work by English-American revolutionary and author Thomas Paine.' },
  { id: 'gutenberg-240', title: 'Religio Medici', author: 'Sir Thomas Browne', category: 'philosophy', desc: 'Religio Medici is the best known work of Sir Thomas Browne, a metaphysical meditation on the relationship between medicine and religion.' },
  { id: 'gutenberg-10031', title: 'Enchiridion of Epictetus', author: 'Epictetus', category: 'philosophy', desc: 'The Enchiridion or Manual of Epictetus is a short manual of Stoic ethical advice compiled by Arrian, a 2nd-century disciple of Epictetus.' },
  { id: 'gutenberg-1400', title: 'Discourses of Epictetus', author: 'Epictetus', category: 'philosophy', desc: 'The Discourses of Epictetus are a series of informal lectures by the Stoic philosopher Epictetus written down by his pupil Arrian.' },
  { id: 'gutenberg-1922', title: 'Meditations', author: 'Marcus Aurelius', category: 'philosophy', desc: 'Meditations is a series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD.' },
  { id: 'gutenberg-1673', title: 'Letters from a Stoic', author: 'Seneca', category: 'philosophy', desc: 'Letters from a Stoic are a collection of 124 letters from Seneca the Younger to his friend Lucilius.' },
  { id: 'gutenberg-2415', title: 'On the Shortness of Life', author: 'Seneca', category: 'philosophy', desc: 'On the Shortness of Life is a moral essay written by Seneca the Younger, a Roman Stoic philosopher.' },
  { id: 'gutenberg-1248', title: 'The Consolation of Philosophy', author: 'Boethius', category: 'philosophy', desc: 'The Consolation of Philosophy is a philosophical work by Boethius, written around the year 524.' },
  { id: 'gutenberg-229', title: 'The Imitation of Christ', author: 'Thomas à Kempis', category: 'philosophy', desc: 'The Imitation of Christ is a Christian devotional book by Thomas à Kempis, first published in 1418.' },
  { id: 'gutenberg-170', title: 'The Holy Bible', author: 'Various', category: 'philosophy', desc: 'The Holy Bible - King James Version, the best known English translation of the Bible.' },
  { id: 'gutenberg-162', title: 'The Book of Psalms', author: 'King James Bible', category: 'poetry', desc: 'The Book of Psalms is a book of the Hebrew Bible and the Christian Old Testament.' },
  { id: 'gutenberg-30', title: 'The Book of Job', author: 'King James Bible', category: 'poetry', desc: 'The Book of Job is a book in the Ketuvim section of the Hebrew Bible and the Christian Old Testament.' },
  { id: 'gutenberg-33258', title: 'The Quran', author: 'Various', category: 'philosophy', desc: 'The Quran is the central religious text of Islam, believed by Muslims to be a revelation from God.' },
  { id: 'gutenberg-23886', title: 'The Dhammapada', author: 'Buddhism', category: 'philosophy', desc: 'The Dhammapada is a collection of sayings of the Buddha in verse form and one of the most widely read and best known Buddhist scriptures.' },
  { id: 'gutenberg-3075', title: 'The Tibetan Book of the Dead', author: 'Buddhism', category: 'philosophy', desc: 'The Tibetan Book of the Dead is a Tibetan Buddhist text that describes the experiences of the consciousness after death.' },
  { id: 'gutenberg-2017', title: 'The Upanishads', author: 'Hinduism', category: 'philosophy', desc: 'The Upanishads are a collection of ancient Sanskrit texts that contain some of the central philosophical concepts and ideas of Hinduism.' },
  { id: 'gutenberg-228', title: 'The Bhagavad Gita', author: 'Hinduism', category: 'philosophy', desc: 'The Bhagavad Gita is a 700-verse Hindu scripture that is part of the Hindu epic Mahabharata.' },
  { id: 'gutenberg-2836', title: 'The Tao Te Ching', author: 'Lao Tzu', category: 'philosophy', desc: 'The Tao Te Ching is a Chinese classic text, written by Lao Tzu, the founder of philosophical Taoism.' },
  { id: 'gutenberg-8525', title: 'The Analects of Confucius', author: 'Confucius', category: 'philosophy', desc: 'The Analects is a book compiling the sayings and ideas attributed to the Chinese philosopher Confucius.' },
  { id: 'gutenberg-347', title: 'The Mencius', author: 'Mencius', category: 'philosophy', desc: 'The Mencius is a collection of anecdotes and conversations of the Confucian thinker Mencius with rulers of various feudal states.' },
  { id: 'gutenberg-13567', title: 'Zhuangzi', author: 'Zhuang Zhou', category: 'philosophy', desc: 'The Zhuangzi is one of the two foundational texts of Taoism, attributed to Zhuang Zhou (Chuang Tzu).' },
  { id: 'gutenberg-1002', title: 'The Histories', author: 'Herodotus', category: 'history', desc: 'The Histories of Herodotus is the founding work of history in Western literature.' },
  { id: 'gutenberg-28027', title: 'The History of the Peloponnesian War', author: 'Thucydides', category: 'history', desc: 'The History of the Peloponnesian War is a historical account of the Peloponnesian War by Thucydides.' },
  { id: 'gutenberg-37200', title: 'Parallel Lives', author: 'Plutarch', category: 'history', desc: 'Parallel Lives, also known as Plutarch\'s Lives, is a series of biographies of famous Greeks and Romans written by Plutarch.' },
  { id: 'gutenberg-1285', title: 'The Twelve Caesars', author: 'Suetonius', category: 'history', desc: 'The Twelve Caesars is a set of twelve biographies of Julius Caesar and the first 11 emperors of the Roman Empire written by Gaius Suetonius Tranquillus.' },
  { id: 'gutenberg-2458', title: 'The Decline and Fall of the Roman Empire', author: 'Edward Gibbon', category: 'history', desc: 'The History of the Decline and Fall of the Roman Empire is a six-volume work by the English historian Edward Gibbon.' },
  { id: 'gutenberg-9', title: 'The Life of Samuel Johnson', author: 'James Boswell', category: 'history', desc: 'The Life of Samuel Johnson is a biography of Dr. Samuel Johnson written by James Boswell, first published in 1791.' },
  { id: 'gutenberg-359', title: 'The History of the Decline and Fall of the Roman Empire', author: 'Edward Gibbon', category: 'history', desc: 'Another edition of Edward Gibbon\'s masterpiece of historical literature.' },
  { id: 'gutenberg-1066', title: 'The Wealth of Nations', author: 'Adam Smith', category: 'philosophy', desc: 'The Wealth of Nations is the magnum opus of the Scottish economist and moral philosopher Adam Smith.' },
  { id: 'gutenberg-1430', title: 'On Liberty', author: 'John Stuart Mill', category: 'philosophy', desc: 'On Liberty is a philosophical essay by John Stuart Mill published in 1859, which applies the system of utilitarianism to society and state.' },
  { id: 'gutenberg-34354', title: 'Utilitarianism', author: 'John Stuart Mill', category: 'philosophy', desc: 'Utilitarianism is an essay written by John Stuart Mill in 1861, explaining utilitarian philosophy.' },
  { id: 'gutenberg-27265', title: 'A System of Logic', author: 'John Stuart Mill', category: 'philosophy', desc: 'A System of Logic is a book by John Stuart Mill, published in 1843, detailing the methods of science and logic.' },
  { id: 'gutenberg-1354', title: 'The Subjection of Women', author: 'John Stuart Mill', category: 'philosophy', desc: 'The Subjection of Women is an essay by John Stuart Mill suggesting that the legal and social subordination of women in Victorian society is wrong.' },
  { id: 'gutenberg-2638', title: 'Two Treatises of Government', author: 'John Locke', category: 'philosophy', desc: 'Two Treatises of Government is a work of political philosophy published anonymously in 1689 by John Locke.' },
  { id: 'gutenberg-10615', title: 'An Essay Concerning Human Understanding', author: 'John Locke', category: 'philosophy', desc: 'An Essay Concerning Human Understanding is a work by John Locke concerning the foundation of human knowledge and understanding.' },
  { id: 'gutenberg-2287', title: 'Leviathan (Variant)', author: 'Thomas Hobbes', category: 'philosophy', desc: 'Leviathan - another edition of Thomas Hobbes\' classic book on the structure of society and legitimate government.' },
  { id: 'gutenberg-2346', title: 'Second Treatise of Government', author: 'John Locke', category: 'philosophy', desc: 'The Second Treatise of Government by John Locke outlines the theory of natural rights and government by consent.' },
  { id: 'gutenberg-1727', title: 'The Odyssey', author: 'Homer', category: 'classic', desc: 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer.' },
  { id: 'gutenberg-6130', title: 'The Iliad', author: 'Homer', category: 'classic', desc: 'The Iliad is an ancient Greek epic poem in dactylic hexameter, traditionally attributed to Homer.' },
  { id: 'gutenberg-1640', title: 'The Aeneid', author: 'Virgil', category: 'classic', desc: 'The Aeneid is a Latin epic poem, written by Virgil between 29 and 19 BC, that tells the legendary story of Aeneas.' },
  { id: 'gutenberg-996', title: 'Metamorphoses', author: 'Ovid', category: 'classic', desc: 'Metamorphoses is a Latin narrative poem by the Roman poet Ovid, considered his magnum opus.' },
  { id: 'gutenberg-237', title: 'The City of God', author: 'Saint Augustine', category: 'philosophy', desc: 'The City of God is a book of Christian philosophy written in Latin by Augustine of Hippo in the early 5th century AD.' },
  { id: 'gutenberg-750', title: 'Confessions', author: 'Saint Augustine', category: 'philosophy', desc: 'The Confessions of Saint Augustine is an autobiographical work by Augustine of Hippo, consisting of 13 books.' },
  { id: 'gutenberg-21089', title: 'Summa Theologica', author: 'Thomas Aquinas', category: 'philosophy', desc: 'Summa Theologiæ is the best-known work of Thomas Aquinas, a compendium of all of the main theological teachings of the Catholic Church.' },
  { id: 'gutenberg-2800', title: 'The Name of the Rose', author: 'Umberto Eco', category: 'mystery', desc: 'The Name of the Rose is the 1980 debut novel by Italian author Umberto Eco, a historical murder mystery set in an Italian monastery.' },
  { id: 'gutenberg-1573', title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', category: 'fiction', desc: 'One Hundred Years of Solitude is a landmark 1967 novel by Colombian author Gabriel García Márquez.' },
  { id: 'gutenberg-4099', title: 'Love in the Time of Cholera', author: 'Gabriel García Márquez', category: 'romance', desc: 'Love in the Time of Cholera is a novel by Colombian author Gabriel García Márquez, first published in 1985.' },
  { id: 'gutenberg-1776', title: 'The Stranger', author: 'Albert Camus', category: 'fiction', desc: 'The Stranger is a 1942 novel by French author Albert Camus. It tells the story of Meursault, an indifferent French Algerian.' },
  { id: 'gutenberg-9296', title: 'The Myth of Sisyphus', author: 'Albert Camus', category: 'philosophy', desc: 'The Myth of Sisyphus is a 1942 philosophical essay by Albert Camus, introducing his philosophy of the absurd.' },
  { id: 'gutenberg-375', title: 'The Trial', author: 'Franz Kafka', category: 'fiction', desc: 'The Trial is a novel written by Franz Kafka between 1914 and 1915, published posthumously in 1925.' },
  { id: 'gutenberg-5200', title: 'Metamorphosis', author: 'Franz Kafka', category: 'fiction', desc: 'Metamorphosis is a novella written by Franz Kafka which was first published in 1915.' },
  { id: 'gutenberg-2246', title: 'The Castle', author: 'Franz Kafka', category: 'fiction', desc: 'The Castle is a 1926 novel by Franz Kafka. In it a protagonist known only as K. arrives in a village and struggles to gain access to the mysterious authorities who govern it.' },
  { id: 'gutenberg-25717', title: 'The Interpretation of Dreams', author: 'Sigmund Freud', category: 'science', desc: 'The Interpretation of Dreams is an 1899 book by Sigmund Freud, the founder of psychoanalysis.' },
  { id: 'gutenberg-28219', title: 'Civilization and Its Discontents', author: 'Sigmund Freud', category: 'science', desc: 'Civilization and Its Discontents is a book by Sigmund Freud, the founder of psychoanalysis, published in 1930.' },
  { id: 'gutenberg-2404', title: 'Totem and Taboo', author: 'Sigmund Freud', category: 'science', desc: 'Totem and Taboo is a 1913 book by Sigmund Freud, the founder of psychoanalysis.' },
  { id: 'gutenberg-3503', title: 'Beyond the Pleasure Principle', author: 'Sigmund Freud', category: 'science', desc: 'Beyond the Pleasure Principle is a 1920 book by Sigmund Freud, the founder of psychoanalysis.' },
  { id: 'gutenberg-7467', title: 'The Ego and the Id', author: 'Sigmund Freud', category: 'science', desc: 'The Ego and the Id is a 1923 paper by Sigmund Freud, the founder of psychoanalysis.' },
  { id: 'gutenberg-27104', title: 'On the Origin of Species', author: 'Charles Darwin', category: 'science', desc: 'On the Origin of Species is a work of scientific literature by Charles Darwin, published on 24 November 1859.' },
  { id: 'gutenberg-3256', title: 'The Voyage of the Beagle', author: 'Charles Darwin', category: 'travel', desc: 'The Voyage of the Beagle is the title most commonly given to the book written by Charles Darwin, first published in 1839.' },
  { id: 'gutenberg-4422', title: 'The Descent of Man', author: 'Charles Darwin', category: 'science', desc: 'The Descent of Man, and Selection in Relation to Sex is a book by English naturalist Charles Darwin, first published in 1871.' },
  { id: 'gutenberg-4408', title: 'The Expression of the Emotions in Man and Animals', author: 'Charles Darwin', category: 'science', desc: 'The Expression of the Emotions in Man and Animals is Charles Darwin\'s third major work of evolutionary theory.' },
  { id: 'gutenberg-18482', title: 'Gulliver\'s Travels', author: 'Jonathan Swift', category: 'adventure', desc: 'Gulliver\'s Travels is a prose satire by Irish writer and clergyman Jonathan Swift, first published in 1726.' },
  { id: 'gutenberg-1152', title: 'A Modest Proposal', author: 'Jonathan Swift', category: 'fiction', desc: 'A Modest Proposal is a Juvenalian satirical essay written and published anonymously by Jonathan Swift in 1729.' },
  { id: 'gutenberg-1064', title: 'Robinson Crusoe (Variant)', author: 'Daniel Defoe', category: 'adventure', desc: 'Robinson Crusoe - another edition of Daniel Defoe\'s classic adventure novel.' },
  { id: 'gutenberg-303', title: 'Moby Dick', author: 'Herman Melville', category: 'adventure', desc: 'Moby Dick - another edition of Herman Melville\'s classic novel.' },
  { id: 'gutenberg-4363', title: 'The Scarlet Letter (Variant)', author: 'Nathaniel Hawthorne', category: 'classic', desc: 'The Scarlet Letter - another edition of Hawthorne\'s classic novel.' },
  { id: 'gutenberg-289', title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'The Adventures of Sherlock Holmes - another edition.' },
  { id: 'gutenberg-325', title: 'The Memoirs of Sherlock Holmes', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'The Memoirs of Sherlock Holmes is a collection of short stories by Arthur Conan Doyle featuring Sherlock Holmes.' },
  { id: 'gutenberg-221', title: 'The Return of Sherlock Holmes', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'The Return of Sherlock Holmes is a collection of 13 Sherlock Holmes stories by Arthur Conan Doyle.' },
  { id: 'gutenberg-2350', title: 'His Last Bow', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'His Last Bow is a collection of 7 Sherlock Holmes stories by Arthur Conan Doyle, first published in 1917.' },
  { id: 'gutenberg-2349', title: 'The Valley of Fear', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'The Valley of Fear is the fourth and final Sherlock Holmes novel by Sir Arthur Conan Doyle.' },
  { id: 'gutenberg-277', title: 'The Sign of Four', author: 'Arthur Conan Doyle', category: 'mystery', desc: 'The Sign of Four is the second novel featuring Sherlock Holmes written by Sir Arthur Conan Doyle.' },
  { id: 'gutenberg-2099', title: 'The Lost World', author: 'Arthur Conan Doyle', category: 'scifi', desc: 'The Lost World is a novel released in 1912 by Sir Arthur Conan Doyle concerning an expedition to a plateau in the Amazon basin.' },
  { id: 'gutenberg-3780', title: 'The Poison Belt', author: 'Arthur Conan Doyle', category: 'scifi', desc: 'The Poison Belt is a science fiction novel by Arthur Conan Doyle, first published in 1913.' },
  { id: 'gutenberg-11', title: 'Alice in Wonderland', author: 'Lewis Carroll', category: 'children', desc: 'Alice\'s Adventures in Wonderland is an 1865 novel written by English author Charles Lutwidge Dodgson under the pseudonym Lewis Carroll.' },
  { id: 'gutenberg-6', title: 'Through the Looking-Glass (Variant)', author: 'Lewis Carroll', category: 'children', desc: 'Through the Looking-Glass - another edition of Lewis Carroll\'s classic.' },
  { id: 'gutenberg-12', title: 'Alice\'s Adventures Under Ground', author: 'Lewis Carroll', category: 'children', desc: 'Alice\'s Adventures Under Ground is the original 1864 manuscript version of Alice\'s Adventures in Wonderland.' },
  { id: 'gutenberg-3391', title: 'The Hunting of the Snark', author: 'Lewis Carroll', category: 'poetry', desc: 'The Hunting of the Snark is a nonsense poem written by Lewis Carroll between 1874 and 1876.' },
  { id: 'gutenberg-476', title: 'Sylvie and Bruno', author: 'Lewis Carroll', category: 'children', desc: 'Sylvie and Bruno is a novel by Lewis Carroll, published in 1889, with two volumes.' },
  { id: 'gutenberg-477', title: 'Sylvie and Bruno Concluded', author: 'Lewis Carroll', category: 'children', desc: 'Sylvie and Bruno Concluded is the second volume of Lewis Carroll\'s novel Sylvie and Bruno.' },
  { id: 'gutenberg-45', title: 'The Adventures of Tom Sawyer (Variant)', author: 'Mark Twain', category: 'children', desc: 'The Adventures of Tom Sawyer - another edition of Mark Twain\'s classic.' },
  { id: 'gutenberg-76', title: 'Adventures of Huckleberry Finn', author: 'Mark Twain', category: 'adventure', desc: 'Adventures of Huckleberry Finn is a novel by Mark Twain, first published in 1884.' },
  { id: 'gutenberg-77', title: 'The Prince and the Pauper (Variant)', author: 'Mark Twain', category: 'children', desc: 'The Prince and the Pauper - another edition.' },
  { id: 'gutenberg-3177', title: 'A Connecticut Yankee in King Arthur\'s Court', author: 'Mark Twain', category: 'scifi', desc: 'A Connecticut Yankee in King Arthur\'s Court is a novel by Mark Twain, published in 1889.' },
  { id: 'gutenberg-2572', title: 'Life on the Mississippi', author: 'Mark Twain', category: 'travel', desc: 'Life on the Mississippi is a memoir by Mark Twain detailing his days as a steamboat pilot on the Mississippi River.' },
  { id: 'gutenberg-119', title: 'The Innocents Abroad', author: 'Mark Twain', category: 'travel', desc: 'The Innocents Abroad is a travel book by Mark Twain, published in 1869, which humorously chronicles what Twain called his "Great Pleasure Excursion".' },
  { id: 'gutenberg-3176', title: 'Roughing It', author: 'Mark Twain', category: 'travel', desc: 'Roughing It is a book of semi-autobiographical travel literature by Mark Twain, published in 1872.' },
  { id: 'gutenberg-3179', title: 'The Gilded Age', author: 'Mark Twain', category: 'fiction', desc: 'The Gilded Age is a novel by Mark Twain and Charles Dudley Warner, first published in 1873.' },
  { id: 'gutenberg-277', title: 'The Tragedy of Pudd\'nhead Wilson (Variant)', author: 'Mark Twain', category: 'fiction', desc: 'The Tragedy of Pudd\'nhead Wilson - another edition.' },
  { id: 'gutenberg-2002', title: 'Following the Equator', author: 'Mark Twain', category: 'travel', desc: 'Following the Equator is a travelogue by Mark Twain, published in 1897.' },
  { id: 'gutenberg-1998', title: 'The Adventures of Huckleberry Finn (Variant)', author: 'Mark Twain', category: 'adventure', desc: 'The Adventures of Huckleberry Finn - another edition.' },
  { id: 'gutenberg-3183', title: 'Tom Sawyer Abroad', author: 'Mark Twain', category: 'children', desc: 'Tom Sawyer Abroad is a novel by Mark Twain, published in 1894, featuring Tom Sawyer and Huckleberry Finn.' },
  { id: 'gutenberg-3186', title: 'Tom Sawyer, Detective', author: 'Mark Twain', category: 'mystery', desc: 'Tom Sawyer, Detective is an 1896 novel by Mark Twain, featuring Tom Sawyer and Huck Finn.' },
  { id: 'gutenberg-1567', title: 'The Man Without a Country', author: 'Edward Everett Hale', category: 'fiction', desc: 'The Man Without a Country is a short story by Edward Everett Hale, first published in 1863.' },
  { id: 'gutenberg-1003', title: 'The Jungle Books', author: 'Rudyard Kipling', category: 'children', desc: 'The Jungle Books are a collection of stories by Rudyard Kipling, including The Jungle Book and The Second Jungle Book.' },
  { id: 'gutenberg-2276', title: 'Kim', author: 'Rudyard Kipling', category: 'fiction', desc: 'Kim is a novel by Nobel Prize-winning English author Rudyard Kipling, first published in serial form in 1900-1901.' },
  { id: 'gutenberg-1695', title: 'Just So Stories', author: 'Rudyard Kipling', category: 'children', desc: 'Just So Stories is a collection of origin stories by Rudyard Kipling, published in 1902.' },
  { id: 'gutenberg-236', title: 'The Jungle Book', author: 'Rudyard Kipling', category: 'children', desc: 'The Jungle Book is a collection of stories by English author Rudyard Kipling.' },
  { id: 'gutenberg-277', title: 'The Second Jungle Book', author: 'Rudyard Kipling', category: 'children', desc: 'The Second Jungle Book is a sequel to The Jungle Book by Rudyard Kipling, first published in 1895.' },
  { id: 'gutenberg-1885', title: 'Captains Courageous', author: 'Rudyard Kipling', category: 'adventure', desc: 'Captains Courageous is an 1897 novel by Rudyard Kipling, that follows the adventures of fifteen-year-old Harvey Cheyne Jr.' },
  { id: 'gutenberg-697', title: 'The Light That Failed', author: 'Rudyard Kipling', category: 'fiction', desc: 'The Light That Failed is the first published novel by Rudyard Kipling, first published in 1891.' },
  { id: 'gutenberg-1938', title: 'Stalky & Co.', author: 'Rudyard Kipling', category: 'fiction', desc: 'Stalky & Co. is a collection of school stories by Rudyard Kipling, published in 1899.' },
  { id: 'gutenberg-1001', title: 'Barrack-Room Ballads', author: 'Rudyard Kipling', category: 'poetry', desc: 'Barrack-Room Ballads is a collection of poems by Rudyard Kipling, first published in 1892.' },
  { id: 'gutenberg-1005', title: 'The Seven Seas', author: 'Rudyard Kipling', category: 'poetry', desc: 'The Seven Seas is a book of poetry by Rudyard Kipling, published in 1896.' },
  { id: 'gutenberg-1505', title: 'The Five Nations', author: 'Rudyard Kipling', category: 'poetry', desc: 'The Five Nations is a collection of poems by Rudyard Kipling, published in 1903.' },
  { id: 'gutenberg-1322', title: 'The Waste Land', author: 'T. S. Eliot', category: 'poetry', desc: 'The Waste Land is a poem by T. S. Eliot, widely regarded as one of the most important poems of the 20th century.' },
  { id: 'gutenberg-1565', title: 'The Love Song of J. Alfred Prufrock', author: 'T. S. Eliot', category: 'poetry', desc: 'The Love Song of J. Alfred Prufrock, commonly known as "Prufrock", is the first professionally published poem by American-born British poet T. S. Eliot.' },
  { id: 'gutenberg-1321', title: 'Murder in the Cathedral', author: 'T. S. Eliot', category: 'drama', desc: 'Murder in the Cathedral is a verse drama by T. S. Eliot, first performed in 1935.' },
  { id: 'gutenberg-1260', title: 'The Hollow Men', author: 'T. S. Eliot', category: 'poetry', desc: 'The Hollow Men is a poem by T. S. Eliot. Its themes are, like many of Eliot\'s poems, overlapping and fragmentary.' },
  { id: 'gutenberg-2419', title: 'Ash Wednesday', author: 'T. S. Eliot', category: 'poetry', desc: 'Ash Wednesday is the first long poem written by T. S. Eliot after his 1927 conversion to Anglicanism.' },
  { id: 'gutenberg-2420', title: 'Four Quartets', author: 'T. S. Eliot', category: 'poetry', desc: 'Four Quartets is a set of four poems written by T. S. Eliot that were published individually over a six-year period.' },
  { id: 'gutenberg-1559', title: 'Ulysses', author: 'James Joyce', category: 'fiction', desc: 'Ulysses is a modernist novel by Irish writer James Joyce.' },
  { id: 'gutenberg-2814', title: 'A Portrait of the Artist as a Young Man', author: 'James Joyce', category: 'fiction', desc: 'A Portrait of the Artist as a Young Man is the first novel of Irish writer James Joyce.' },
  { id: 'gutenberg-1032', title: 'Dubliners', author: 'James Joyce', category: 'fiction', desc: 'Dubliners is a collection of fifteen short stories by James Joyce, first published in 1914.' },
  { id: 'gutenberg-2833', title: 'Finnegans Wake', author: 'James Joyce', category: 'fiction', desc: 'Finnegans Wake is a novel by Irish writer James Joyce, significant for its experimental style and reputation as one of the most difficult works of fiction in the Western canon.' },
  { id: 'gutenberg-2571', title: 'To the Lighthouse', author: 'Virginia Woolf', category: 'fiction', desc: 'To the Lighthouse is a 1927 novel by Virginia Woolf, one of her most famous works.' },
  { id: 'gutenberg-2848', title: 'Mrs. Dalloway', author: 'Virginia Woolf', category: 'fiction', desc: 'Mrs. Dalloway is a novel by Virginia Woolf that details a day in the life of Clarissa Dalloway, a fictional high-society woman in post-First World War England.' },
  { id: 'gutenberg-2781', title: 'Orlando', author: 'Virginia Woolf', category: 'fiction', desc: 'Orlando: A Biography is a novel by Virginia Woolf, first published on 11 October 1928.' },
  { id: 'gutenberg-3106', title: 'The Waves', author: 'Virginia Woolf', category: 'fiction', desc: 'The Waves is a 1931 novel by Virginia Woolf, considered by many to be her most experimental work.' },
  { id: 'gutenberg-1132', title: 'A Room of One\'s Own', author: 'Virginia Woolf', category: 'philosophy', desc: 'A Room of One\'s Own is an extended essay by Virginia Woolf, first published in September 1929.' },
  { id: 'gutenberg-566', title: 'Three Guineas', author: 'Virginia Woolf', category: 'philosophy', desc: 'Three Guineas is a book-length essay by Virginia Woolf, published in 1938.' },
  { id: 'gutenberg-1015', title: 'The Second Sex', author: 'Simone de Beauvoir', category: 'philosophy', desc: 'The Second Sex is a 1949 book by the French existentialist philosopher Simone de Beauvoir.' },
  { id: 'gutenberg-10', title: 'The Interpretation of Dreams', author: 'Sigmund Freud', category: 'science', desc: 'The Interpretation of Dreams by Sigmund Freud.' },
  { id: 'gutenberg-2000', title: 'The General Theory of Employment, Interest and Money', author: 'John Maynard Keynes', category: 'philosophy', desc: 'The General Theory of Employment, Interest and Money is a book by English economist John Maynard Keynes, published in 1936.' },
  { id: 'gutenberg-4404', title: 'The Road to Serfdom', author: 'Friedrich Hayek', category: 'philosophy', desc: 'The Road to Serfdom is a book written between 1940 and 1943 by Austrian-British economist and philosopher Friedrich Hayek.' },
  { id: 'gutenberg-2484', title: 'Capital, Volume I', author: 'Karl Marx', category: 'philosophy', desc: 'Capital: A Critique of Political Economy is a foundational theoretical text in materialist philosophy, economics and politics by Karl Marx.' },
  { id: 'gutenberg-97', title: 'The Communist Manifesto', author: 'Karl Marx and Friedrich Engels', category: 'philosophy', desc: 'The Communist Manifesto - another edition.' },
  { id: 'gutenberg-2483', title: 'Economic and Philosophical Manuscripts', author: 'Karl Marx', category: 'philosophy', desc: 'Economic and Philosophical Manuscripts of 1844 are a series of notes written by Karl Marx between April and August 1844.' },
  { id: 'gutenberg-5000', title: 'Being and Time', author: 'Martin Heidegger', category: 'philosophy', desc: 'Being and Time is the 1927 magnum opus of German philosopher Martin Heidegger and a key document of existentialism.' },
  { id: 'gutenberg-28724', title: 'Thus Spoke Zarathustra', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'Thus Spoke Zarathustra is a philosophical novel by German philosopher Friedrich Nietzsche.' },
  { id: 'gutenberg-4363', title: 'Beyond Good and Evil', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'Beyond Good and Evil: Prelude to a Philosophy of the Future is a book by philosopher Friedrich Nietzsche.' },
  { id: 'gutenberg-19322', title: 'The Birth of Tragedy', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'The Birth of Tragedy is a book by Friedrich Nietzsche, published in 1872, his first book.' },
  { id: 'gutenberg-5286', title: 'On the Genealogy of Morals', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'On the Genealogy of Morals is a work by Friedrich Nietzsche, consisting of a preface and three interrelated treatises.' },
  { id: 'gutenberg-2638', title: 'Twilight of the Idols', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'Twilight of the Idols, or, How to Philosophize with a Hammer is a book by Friedrich Nietzsche, written in 1888 and published in 1889.' },
  { id: 'gutenberg-37156', title: 'The Gay Science', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'The Gay Science is a book by Friedrich Nietzsche, first published in 1882.' },
  { id: 'gutenberg-3330', title: 'Ecce Homo', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'Ecce Homo is an autobiography by Friedrich Nietzsche, written in 1888 and published in 1908.' },
  { id: 'gutenberg-38060', title: 'The Will to Power', author: 'Friedrich Nietzsche', category: 'philosophy', desc: 'The Will to Power is a book of notes drawn from the literary remains of philosopher Friedrich Nietzsche by his sister Elisabeth Förster-Nietzsche.' },
  { id: 'gutenberg-29225', title: 'Mere Christianity', author: 'C. S. Lewis', category: 'philosophy', desc: 'Mere Christianity is a theological book by C. S. Lewis, adapted from a series of BBC radio talks made between 1941 and 1944.' },
  { id: 'gutenberg-10092', title: 'The Screwtape Letters', author: 'C. S. Lewis', category: 'fiction', desc: 'The Screwtape Letters is a satirical Christian apologetics novel written by C. S. Lewis and first published in February 1942.' },
  { id: 'gutenberg-551', title: 'The Chronicles of Narnia', author: 'C. S. Lewis', category: 'children', desc: 'The Chronicles of Narnia is a series of seven fantasy novels for children written by C. S. Lewis.' },
  { id: 'gutenberg-10093', title: 'The Lion, the Witch and the Wardrobe', author: 'C. S. Lewis', category: 'fantasy', desc: 'The Lion, the Witch and the Wardrobe is a fantasy novel for children by C. S. Lewis, published in 1950.' },
  { id: 'gutenberg-22886', title: 'The Lord of the Rings', author: 'J. R. R. Tolkien', category: 'fantasy', desc: 'The Lord of the Rings is an epic high fantasy novel by the English author and scholar J. R. R. Tolkien.' },
  { id: 'gutenberg-174', title: 'The Hobbit', author: 'J. R. R. Tolkien', category: 'fantasy', desc: 'The Hobbit, or There and Back Again is a children\'s fantasy novel by English author J. R. R. Tolkien.' },
  { id: 'gutenberg-345', title: 'The Silmarillion', author: 'J. R. R. Tolkien', category: 'fantasy', desc: 'The Silmarillion is a collection of mythopoeic works by English writer J. R. R. Tolkien, edited and published posthumously by his son.' },
]

// 去重并生成最终数据
const seen = new Set()
const uniqueBooks = []

for (const b of booksData) {
  if (seen.has(b.id)) continue
  seen.add(b.id)
  
  const bookId = b.id.replace('gutenberg-', '')
  uniqueBooks.push({
    id: b.id,
    title: b.title,
    author: b.author,
    description: b.desc,
    cover: `https://www.gutenberg.org/cache/epub/${bookId}/pg${bookId}.cover.medium.jpg`,
    downloadUrl: `https://www.gutenberg.org/ebooks/${bookId}.epub3.images`,
    category: b.category,
    language: 'en',
    publisher: 'Project Gutenberg',
    publishDate: '',
    source: 'Project Gutenberg',
    readUrl: `https://www.gutenberg.org/ebooks/${bookId}`,
    readType: 'iframe'
  })
}

// 添加日文图书
const japaneseBooks = [
  { id: 'aozora-natsume-kokoro', title: 'こころ', author: '夏目漱石', category: 'classic', desc: 'こころは夏目漱石の小説。1914年発表。漱石晩年の代表作の一つ。' },
  { id: 'aozora-natsume-neko', title: '吾輩は猫である', author: '夏目漱石', category: 'classic', desc: '吾輩は猫であるは夏目漱石の小説。1905年発表。猫の視点から人間社会を皮肉たっぷりに描く。' },
  { id: 'aozora-natsume-bocchan', title: '坊っちゃん', author: '夏目漱石', category: 'classic', desc: '坊っちゃんは夏目漱石の短編小説。1906年発表。若教師の地方での奮闘記。' },
  { id: 'aozora-natsume-sorekara', title: 'それから', author: '夏目漱石', category: 'classic', desc: 'それからは夏目漱石の長編小説。1909年発表。明治期の知識人の苦悩を描く。' },
  { id: 'aozora-natsume-monn', title: '門', author: '夏目漱石', category: 'classic', desc: '門は夏目漱石の小説。1910年発表。夫婦の日常と内面の葛藤を描く。' },
  { id: 'aozora-natsume-gyoretu', title: '行人', author: '夏目漱石', category: 'classic', desc: '行人は夏目漱石の小説。1912年発表。明治末期の知識人の孤独と不安を描く。' },
  { id: 'aozora-natsume-anshin', title: '安部公房', author: '安部公房', category: 'fiction', desc: '安部公房の作品群。' },
  { id: 'aozora-akutagawa-rashomon', title: '羅生門', author: '芥川龍之介', category: 'classic', desc: '羅生門は芥川龍之介の短編小説。1915年発表。平安末期の京都を舞台に。' },
  { id: 'aozora-akutagawa-hana', title: '鼻', author: '芥川龍之介', category: 'classic', desc: '鼻は芥川龍之介の短編小説。1916年発表。内供の長い鼻をめぐる物語。' },
  { id: 'aozora-akutagawa-kumo', title: '蜘蛛の糸', author: '芥川龍之介', category: 'children', desc: '蜘蛛の糸は芥川龍之介の童話。1918年発表。地獄に落ちた犍陀多の物語。' },
  { id: 'aozora-akutagawa-jigokuhen', title: '地獄変', author: '芥川龍之介', category: 'classic', desc: '地獄変は芥川龍之介の短編小説。1918年発表。絵師良秀の芸術と狂気。' },
  { id: 'aozora-akutagawa-kappa', title: '河童', author: '芥川龍之介', category: 'fantasy', desc: '河童は芥川龍之介の風刺小説。1927年発表。河童の国を訪れた人間の物語。' },
  { id: 'aozora-dazai-ningen', title: '人間失格', author: '太宰治', category: 'classic', desc: '人間失格は太宰治の自伝的小説。1948年発表。葉蔵の自己喪失の物語。' },
  { id: 'aozora-dazai-sayo', title: '斜陽', author: '太宰治', category: 'classic', desc: '斜陽は太宰治の小説。1947年発表。没落貴族の母女の物語。' },
  { id: 'aozora-dazai-runrun', title: '走れメロス', author: '太宰治', category: 'classic', desc: '走れメロスは太宰治の短編小説。1940年発表。友情と信頼の物語。' },
  { id: 'aozora-dazai-viyonnosama', title: 'ヴィヨンの妻', author: '太宰治', category: 'fiction', desc: 'ヴィヨンの妻は太宰治の短編小説。1947年発表。' },
  { id: 'aozora-dazai-otogizoshi', title: 'お伽草紙', author: '太宰治', category: 'children', desc: 'お伽草紙は太宰治による日本の昔ばなしの書き換え作品。' },
  { id: 'aozora-dazai-tsugaru', title: '津軽', author: '太宰治', category: 'travel', desc: '津軽は太宰治の紀行文。1944年発表。故郷・青森県津軽地方への旅。' },
  { id: 'aozora-miyazawa-ginga', title: '銀河鉄道の夜', author: '宮沢賢治', category: 'children', desc: '銀河鉄道の夜は宮沢賢治の童話。1934年遺稿発表。ジョバンニの銀河の旅。' },
  { id: 'aozora-miyazawa-amas', title: '注文の多い料理店', author: '宮沢賢治', category: 'children', desc: '注文の多い料理店は宮沢賢治の童話。1924年発表。' },
  { id: 'aozora-miyazawa-kaze', title: '風の又三郎', author: '宮沢賢治', category: 'children', desc: '風の又三郎は宮沢賢治の童話。1934年発表。' },
  { id: 'aozora-miyazawa-matasa', title: 'マッチ売りの少女', author: '宮沢賢治', category: 'children', desc: 'マッチ売りの少女（宮沢賢治版）' },
  { id: 'aozora-miyazawa-gan', title: '雁の童子', author: '宮沢賢治', category: 'children', desc: '雁の童子は宮沢賢治の童話。' },
  { id: 'aozora-miyazawa-ogino', title: 'ヲヅォヅォムを殲せ', author: '宮沢賢治', category: 'children', desc: '宮沢賢治の作品。' },
  { id: 'aozora-akutagawa-imogayu', title: '芋粥', author: '芥川龍之介', category: 'classic', desc: '芋粥は芥川龍之介の短編小説。1916年発表。' },
  { id: 'aozora-akutagawa-mandara', title: '曼陀羅', author: '芥川龍之介', category: 'classic', desc: '曼陀羅は芥川龍之介の作品。' },
  { id: 'aozora-akutagawa-toshishun', title: '杜子春', author: '芥川龍之介', category: 'children', desc: '杜子春は芥川龍之介の短編小説。1920年発表。中国伝説を素材に。' },
  { id: 'aozora-akutagawa-kogane', title: '黄金時代', author: '芥川龍之介', category: 'classic', desc: '黄金時代は芥川龍之介の作品。' },
  { id: 'aozora-akutagawa-hiroshi', title: '侏儒の言葉', author: '芥川龍之介', category: 'philosophy', desc: '侏儒の言葉は芥川龍之介の随筆。' },
  { id: 'aozora-akutagawa-shogai', title: 'ある阿呆の一生', author: '芥川龍之介', category: 'classic', desc: 'ある阿呆の一生は芥川龍之介の作品。' },
  { id: 'aozora-natsume-yume', title: '夢十夜', author: '夏目漱石', category: 'fiction', desc: '夢十夜は夏目漱石の短編集。1908年発表。' },
  { id: 'aozora-natsume-akakage', title: '二百十日', author: '夏目漱石', category: 'classic', desc: '二百十日は夏目漱石の小説。' },
  { id: 'aozora-natsume-kusamakura', title: '草枕', author: '夏目漱石', category: 'classic', desc: '草枕は夏目漱石の小説。1906年発表。' },
  { id: 'aozora-natsume-nowaki', title: '野分', author: '夏目漱石', category: 'classic', desc: '野分は夏目漱石の小説。' },
  { id: 'aozora-mori-takahito', title: '舞姫', author: '森鷗外', category: 'classic', desc: '舞姫は森鷗外の短編小説。1890年発表。' },
  { id: 'aozora-mori-utagawa', title: 'うたかたの記', author: '森鷗外', category: 'classic', desc: 'うたかたの記は森鷗外の作品。' },
  { id: 'aozora-mori-sekibai', title: '赤い髪', author: '森鷗外', category: 'classic', desc: '赤い髪は森鷗外の作品。' },
  { id: 'aozora-mori-kobayashi', title: '雁', author: '森鷗外', category: 'classic', desc: '雁は森鷗外の小説。' },
  { id: 'aozora-mori-aburauo', title: '阿部一族', author: '森鷗外', category: 'history', desc: '阿部一族は森鷗外の歴史小説。' },
  { id: 'aozora-mori-saigo', title: '最後の一句', author: '森鷗外', category: 'classic', desc: '最後の一句は森鷗外の作品。' },
  { id: 'aozora-shimazaki-bodaiju', title: '菩提樹', author: '島崎藤村', category: 'poetry', desc: '菩提樹は島崎藤村の詩集。' },
  { id: 'aozora-shimazaki-hakai', title: '破戒', author: '島崎藤村', category: 'classic', desc: '破戒は島崎藤村の小説。1906年発表。' },
  { id: 'aozora-tayama-kai', title: '田山花袋', author: '田山花袋', category: 'fiction', desc: '田山花袋の作品群。' },
  { id: 'aozora-kyouka-onna', title: '泉鏡花', author: '泉鏡花', category: 'fiction', desc: '泉鏡花の作品群。' },
  { id: 'aozora-higuchi-ie', title: '樋口一葉', author: '樋口一葉', category: 'classic', desc: '樋口一葉の作品群。' },
  { id: 'aozora-yosano-twilight', title: '与謝野晶子', author: '与謝野晶子', category: 'poetry', desc: '与謝野晶子の歌集。' },
  { id: 'aozora-kitamura-kocho', title: '北村透谷', author: '北村透谷', category: 'poetry', desc: '北村透谷の作品。' },
  { id: 'aozora-kawakami-onna', title: '川上眉山', author: '川上眉山', category: 'fiction', desc: '川上眉山の作品。' },
  { id: 'aozora-hirotsu-onna', title: '広津柳浪', author: '広津柳浪', category: 'fiction', desc: '広津柳浪の作品。' },
]

for (const b of japaneseBooks) {
  if (seen.has(b.id)) continue
  seen.add(b.id)
  
  uniqueBooks.push({
    id: b.id,
    title: b.title,
    author: b.author,
    description: b.desc,
    cover: `https://picsum.photos/seed/${b.id}/300/400`,
    downloadUrl: '',
    category: b.category,
    language: 'ja',
    publisher: '青空文庫',
    publishDate: '',
    source: '青空文庫',
    readUrl: '',
    readType: 'link'
  })
}

// 保存
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
fs.writeFileSync(OUTPUT_FILE, JSON.stringify(uniqueBooks, null, 2), 'utf-8')

console.log(`Generated ${uniqueBooks.length} books`)
console.log(`English: ${uniqueBooks.filter(b => b.language === 'en').length}`)
console.log(`Japanese: ${uniqueBooks.filter(b => b.language === 'ja').length}`)
console.log(`Categories: ${[...new Set(uniqueBooks.map(b => b.category))].join(', ')}`)
